sudo: required
dist: trusty

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs-v2.5.0"
  - "4"
  - "5"

notifications:
  email:
    recipients:
      - adam@apiary.io
      - kubula@apiary.io
    on_success: change
    on_failure: always

after_success:
  - ./scripts/coveralls
