sudo: "required"
dist: "trusty"
language: "node_js"
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
before_install:
  - "npm -g install npm@latest"
before_script:
  - "npm run lint"
script:
  - "npm test"
after_success:
  - "npm run coveralls"
