language: node_js
node_js:
  - "iojs-v2.5.0"
  - "0.10"
  - "0.12"
sudo: false
notifications:
  email:
    recipients:
      - adam@apiary.io
    on_success: change
    on_failure: always
after_success:
  - ./scripts/coveralls
