language: node_js
node_js:
  - 0.8
  - 0.10
notifications:
  email:
    recipients:
      - z@apiary.io
      - ladislav@apiary.io
    on_success: change
    on_failure: always
after_success:
  - ./scripts/coveralls

