language: node_js
node_js:
  - 0.10
before_install:
  - npm install -g npm@~1.4.6
notifications:
  email:
    recipients:
      - z@apiary.io
      - ladislav@apiary.io
      - adam@apiary.io
    on_success: change
    on_failure: always
  hipchat:
    rooms:
      secure: "pKDBboEmYne/Hs9qUSCQCgWZ9insdvgvB0DyMYYpO8RHgNOAhpcY1Kz/wTmFtm1k2HjGNGx1OVgVhOYXwIiJQZbmiUT4gVDEUtmpSgiW3/uQATgaPFUAsaIFqemTPgI6Q8RfsJZQk1kRMioZhk0ldQY5A+AUIKYKg1BFiOsrO1s="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
after_success:
  - ./scripts/coveralls

