# GH_TOKEN and NPM_TOKEN are expected to be set
# in https://travis-ci.org/apiaryio/dredd/settings
dist: "trusty"
language: "node_js"
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
before_install:
  - "npm -g install npm@6"
  - "pyenv global 3.6"
  - "pip install pip --upgrade"
install:
  - "npm install --no-optional"
  - "pip install --user -r docs/requirements.txt"
jobs:
  include:
    # stage 1, all following runs in parallel:
    - stage: "quality checks & tests"
      env: "JOB=quality_checks"
      script: "npm run ci:lint"
    - env: "JOB=docs_build_dry_run" # why dry run? because production build happens directly on ReadTheDocs infrastructure
      script: "npm run ci:docs"
    - env: "JOB=node6"
      node_js: "6"
      script: "npm run ci:test"
    - env: "JOB=node8"
      node_js: "8"
      script: "npm run ci:test"
    - env: "JOB=node10"
      script: "npm run ci:test"

    # stage 2
    - stage: "semantic release"
      script: "npm run ci:release"
      if: fork = false AND branch = master AND type = push
