environment:
  nodejs_version: '12'
install:
  - ps: Install-Product node 12
  - 'npm -g install npm@6'
  - 'npm install -g yarn'
  - "set PATH=%APPDATA%\\npm;%PATH%"
  - 'yarn install'
cache:
  - 'node_modules -> yarn.lock'
  - "%APPDATA%\\npm-cache -> yarn.lock"
build: off
test_script:
  - 'node --version'
  - 'npm --version'
  - 'yarn --version'
  - 'yarn build'
  - 'yarn ci:test'
