site_name: Dredd

pages:
  - Dredd:
    - About Dredd: index.md
    - Usage: usage.md
    - Quickstart: quickstart.md
    - Overview: overview.md
  - Hooks:
    - About Hooks: hooks.md
    - Supported Languages:
      - Go: hooks-go.md
      - JavaScript (Sandboxed): hooks-js-sandbox.md
      - Node.js: hooks-nodejs.md
      - Perl: hooks-perl.md
      - PHP: hooks-php.md
      - Python: hooks-python.md
      - Ruby: hooks-ruby.md
    - Other Languages: hooks-new-language.md

  - Example:
    - Full Example: example.md

repo_url: 'https://github.com/apiaryio/dredd'

theme: readthedocs
markdown_extensions:
  - toc:
      permalink: true
