site_name: Dredd
pages:
- Dredd:
  - Home: index.md
  - Overview: overview.md
- Using Dredd:
  - Usage: usage.md
  - Hooks: hooks.md
- Example:
  - Full Example: example.md

repo_url: 'https://github.com/apiaryio/dredd'
